/**
 * WindowsTaskSchedulerAdapter (spec §3).
 *
 * Manages a single user-level scheduled task ("VoltMind Autopilot") that runs
 * `voltmind autopilot --repo <path>` on user logon. Uses the PowerShell
 * ScheduledTasks module with JSON output for stable, non-localized status
 * parsing (never `schtasks.exe` human text). Task XML registration uses
 * `schtasks.exe /Create /TN ... /XML <file>` (XML is generated by the pure
 * `createWindowsTaskXml()`).
 *
 * The adapter ONLY keeps the autopilot process running. It does not submit
 * jobs, run `jobs work`, manage leases, or persist business state. The task
 * action is always plain `voltmind autopilot --repo <path>` — never
 * `--no-worker`, never `jobs work`.
 */

import { existsSync, mkdirSync, rmSync, unlinkSync, writeFileSync } from 'fs';
import { join } from 'path';
import { execFileSync } from 'child_process';
import { voltmindPath } from '../config.ts';
import {
  createWindowsTaskXml,
  DEFAULT_WINDOWS_TASK_NAME,
  DEFAULT_RESTART_INTERVAL_MINUTES,
  DEFAULT_RESTART_COUNT,
} from './windows-task-xml.ts';
import { buildCliArgv, type CliInvocation } from './cli-invocation.ts';
import {
  AUTOPILOT_ERRORS,
  AutopilotError,
} from './diagnostics.ts';
import type {
  AutopilotInstallContext,
  AutopilotInstallResult,
  AutopilotProcessManagerAdapter,
  AutopilotProcessManagerStatus,
  AutopilotStatusContext,
  AutopilotUninstallContext,
  AutopilotUninstallResult,
} from './adapter.ts';

export const WINDOWS_TASK_NAME = DEFAULT_WINDOWS_TASK_NAME;

function taskXmlPath(): string {
  return voltmindPath('runtime', 'autopilot-task.xml');
}

function runPowerShell(script: string, opts: { timeoutMs?: number } = {}): string {
  try {
    return execFileSync(
      'powershell.exe',
      ['-NoProfile', '-NonInteractive', '-Command', script],
      { encoding: 'utf8', timeout: opts.timeoutMs ?? 30_000, stdio: ['ignore', 'pipe', 'pipe'], env: process.env },
    );
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    throw new AutopilotError({
      code: AUTOPILOT_ERRORS.WINDOWS_TASK_QUERY_FAILED,
      stage: 'task-registration',
      message: `PowerShell command failed: ${msg}`,
    });
  }
}

/**
 * Query the task state via the ScheduledTasks module, returning stable JSON.
 * Never parses localized `schtasks` text.
 */
function queryTask(): { exists: boolean; state: string; lastResult?: string; lastRunTime?: string } {
  const script = `
$ErrorActionPreference = 'SilentlyContinue'
$t = Get-ScheduledTask -TaskName '${WINDOWS_TASK_NAME.replace(/'/g, "''")}'
if ($null -eq $t) { '{"exists":false}'; exit }
$info = $t | Get-ScheduledTaskInfo
$obj = @{
  exists = $true
  state = [string]$t.State
  lastResult = [string]$info.LastTaskResult
  lastRunTime = if ($info.LastRunTime) { $info.LastRunTime.ToString('o') } else { $null }
}
$obj | ConvertTo-Json -Compress
`;
  const out = runPowerShell(script);
  try {
    return JSON.parse(out.trim());
  } catch {
    return { exists: false, state: 'Unknown' };
  }
}

export class WindowsTaskSchedulerAdapter implements AutopilotProcessManagerAdapter {
  readonly target = 'windows-task' as const;

  async detect(): Promise<{ target: 'windows-task' }> {
    return { target: 'windows-task' };
  }

  async install(context: AutopilotInstallContext): Promise<AutopilotInstallResult> {
    // Build the task action: `voltmind autopilot --repo <path> [--runtime-env-file <path>]`
    // NEVER `--no-worker` (spec §3.1 / §20).
    const subcommand = ['autopilot', '--repo', context.repoPath];
    if (context.runtimeEnvFile) {
      subcommand.push('--runtime-env-file', context.runtimeEnvFile);
    }
    const argv = buildCliArgv(context.cliInvocation, subcommand);
    // Task Scheduler <Command> + <Arguments> map to CreateProcess. For a .cmd
    // shim the executable is ComSpec and the framing (/d /s /c "<cmd>") lives
    // in the prefix args; for a native .exe the prefix args are empty.
    const executable = context.cliInvocation.executable;
    const argumentsAfterExe = argv;
    const xml = createWindowsTaskXml({
      taskName: WINDOWS_TASK_NAME,
      executable,
      arguments: argumentsAfterExe,
      workingDirectory: context.workingDirectory ?? context.repoPath,
      userId: context.userId,
      // CalendarTrigger repeats every minute for every day, starting now.
      // It is a recovery backstop for task termination paths that Task
      // Scheduler does not classify as a restart-on-failure event.
      recoveryStartBoundary: new Date().toISOString(),
      restartIntervalMinutes: DEFAULT_RESTART_INTERVAL_MINUTES,
      restartCount: DEFAULT_RESTART_COUNT,
    });

    const xmlPath = taskXmlPath();
    mkdirSync(voltmindPath('runtime'), { recursive: true });
    // schtasks.exe requires UTF-16LE with a BOM for the XML file.
    writeFileSync(xmlPath, '\uFEFF' + xml, { encoding: 'utf16le' });

    // Register / overwrite the task from XML. `schtasks /Create /F` overwrites.
    try {
      execFileSync(
        'schtasks.exe',
        ['/Create', '/TN', WINDOWS_TASK_NAME, '/XML', xmlPath, '/F'],
        { encoding: 'utf8', timeout: 30_000, stdio: ['ignore', 'pipe', 'pipe'], env: process.env },
      );
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      throw new AutopilotError({
        code: AUTOPILOT_ERRORS.WINDOWS_TASK_REGISTER_FAILED,
        stage: 'task-registration',
        message: `Failed to register Windows scheduled task "${WINDOWS_TASK_NAME}": ${msg}`,
        actionableHint: 'Ensure you are logged in and Task Scheduler service is running.',
      });
    }

    // Start the task immediately.
    let started = false;
    try {
      execFileSync(
        'schtasks.exe',
        ['/Run', '/TN', WINDOWS_TASK_NAME],
        { encoding: 'utf8', timeout: 15_000, stdio: ['ignore', 'pipe', 'pipe'], env: process.env },
      );
      started = true;
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      throw new AutopilotError({
        code: AUTOPILOT_ERRORS.WINDOWS_TASK_START_FAILED,
        stage: 'task-start',
        message: `Task registered but failed to start: ${msg}`,
        actionableHint: 'Check Task Scheduler UI for the VoltMind Autopilot task.',
      });
    }

    return {
      target: 'windows-task',
      registered: true,
      started,
      schedulerName: WINDOWS_TASK_NAME,
    };
  }

  async uninstall(_context: AutopilotUninstallContext): Promise<AutopilotUninstallResult> {
    let stopped = false;
    let removed = false;
    // End any running instance, then delete.
    try {
      runPowerShell(`Stop-ScheduledTask -TaskName '${WINDOWS_TASK_NAME.replace(/'/g, "''")}' -ErrorAction SilentlyContinue`);
      stopped = true;
    } catch { /* best-effort */ }
    try {
      runPowerShell(`Unregister-ScheduledTask -TaskName '${WINDOWS_TASK_NAME.replace(/'/g, "''")}' -Confirm:$false -ErrorAction SilentlyContinue`);
      removed = true;
    } catch { /* best-effort */ }
    // Clean up the generated XML file (we own it).
    const xmlPath = taskXmlPath();
    if (existsSync(xmlPath)) {
      try { unlinkSync(xmlPath); } catch { /* best-effort */ }
    }
    return { stopped, removed, detail: removed ? 'Task deleted' : 'Task not found' };
  }

  async status(_context: AutopilotStatusContext): Promise<AutopilotProcessManagerStatus> {
    const info = queryTask();
    // Ready means the task is registered and eligible for a future trigger;
    // it does not mean an Autopilot process is currently alive. Treating it as
    // running masked the exact failed-recovery state this adapter must report.
    const running = info.exists && info.state === 'Running';
    return {
      target: 'windows-task',
      registered: info.exists,
      running,
      lastResult: info.lastResult,
      lastStartedAt: info.lastRunTime,
      currentState: info.state,
    };
  }
}

export const windowsTaskSchedulerAdapter = new WindowsTaskSchedulerAdapter();
