import type { Operation } from './operations.ts';

export const VOLTMIND_MVP_CLI_COMMANDS = new Set([
  'init',
  'reinit-pglite',
  'config',
  'storage',
  'providers',
  'sources',
  'status',
  'daemon',
  'doctor',
  'upgrade',
  'post-upgrade',
  'check-update',
  'self-upgrade',
 'apply-migrations',
 'migrate',
 'get',
  'put',
  'delete',
  'restore',
  'list',
  'search',
  'query',
  'ask',
  'import',
  'files',
  'capture',
  'sync',
  'embed',
  'extract',
  'extract-conversation-facts',
  'enrich',
  'transcripts',
  'tags',
  'tag',
  'untag',
  'link',
  'unlink',
 'backlinks',
 'graph',
 'graph-query',
 'timeline',
  'timeline-add',
  'salience',
  'anomalies',
  'whoknows',
  'calibration',
  'takes',
  'conversation-parser',
  'recall',
  'forget',
  'candidates',
  'actions',
  'autopilot',
  'serve',
  'call',
  'jobs',
  'stats',
  'health',
  'history',
  'version',
]);

export const VOLTMIND_MVP_OPERATION_NAMES = new Set([
  'get_page',
  'put_page',
  'delete_page',
  'restore_page',
  'list_pages',
  'search',
  'query',
  'get_tags',
  'add_tag',
  'remove_tag',
  'add_link',
  'remove_link',
  'get_links',
  'get_backlinks',
  'traverse_graph',
  'add_timeline_entry',
  'get_timeline',
  'get_stats',
  'get_health',
  'get_brain_identity',
  'get_status_snapshot',
  'run_doctor',
  'get_versions',
  'sync_brain',
  'put_raw_data',
  'get_raw_data',
  'preview_signal_enrichment',
  'apply_signal_enrichment',
  'get_job',
  'list_jobs',
  'cancel_job',
  'get_job_progress',
  'get_job_failure_report',
  'get_job_checkpoints',
  'get_job_undo_report',
  'plan_job_batch',
  'action_scan',
  'action_list',
  'action_get',
  'action_approve',
  'action_run',
  'sources_add',
  'sources_list',
  'sources_remove',
  'sources_status',
  'get_recent_salience',
  'find_anomalies',
  'find_experts',
  'get_calibration_profile',
  'get_recent_transcripts',
  'find_contradictions',
  'find_trajectory',
  'takes_list',
  'takes_search',
  'recall',
  'preview_forget_fact',
  'apply_forget_fact',
  'propose_extraction_candidates',
  'preview_candidate_apply',
  'apply_candidate',
  'reject_candidate',
]);

const VOLTMIND_MVP_OPERATION_DESCRIPTIONS: Record<string, string> = {
  get_page: 'Read a VoltMind page by slug.',
  put_page: 'Write or update a VoltMind markdown page, then refresh chunks, embeddings, tags, links, and timeline entries.',
  delete_page: 'Soft-delete a VoltMind page so it is hidden from normal reads and search.',
  restore_page: 'Restore a soft-deleted VoltMind page.',
  list_pages: 'List VoltMind pages with optional type, tag, recency, and limit filters.',
  search: 'Keyword search over VoltMind pages using full-text search.',
  query: 'Hybrid search over VoltMind pages using vector, keyword, and optional multi-query expansion.',
  add_tag: 'Add a tag to a VoltMind page.',
  remove_tag: 'Remove a tag from a VoltMind page.',
  get_tags: 'List tags for a VoltMind page.',
  add_link: 'Create a typed link between two VoltMind pages.',
  remove_link: 'Remove a link between two VoltMind pages.',
  get_links: 'List outgoing links from a VoltMind page.',
  get_backlinks: 'List incoming links to a VoltMind page.',
  traverse_graph: 'Traverse the VoltMind page graph from a starting page.',
  add_timeline_entry: 'Add a timeline entry to a VoltMind page.',
  get_timeline: 'Read timeline entries for a VoltMind page.',
  get_stats: 'Return basic VoltMind page, chunk, embedding, link, tag, and timeline counts.',
  get_health: 'Return basic VoltMind health signals such as embedding coverage and stale pages.',
  run_doctor: 'Run VoltMind runtime health checks.',
  get_versions: 'List version history for a VoltMind page.',
  get_brain_identity: 'Return VoltMind runtime identity and basic counters.',
  get_status_snapshot: 'Return a compact VoltMind runtime status snapshot.',
  sync_brain: 'Sync a local source repository into VoltMind.',
  put_raw_data: 'Store raw source data for a VoltMind page as provenance for later citation or enrichment review.',
  get_raw_data: 'Retrieve raw source data attached to a VoltMind page.',
  preview_signal_enrichment: 'Preview source-backed person/company signal enrichment without mutating brain content.',
  apply_signal_enrichment: 'Apply source-backed person/company signal enrichment with explicit confirmation.',
  get_job: 'Get VoltMind job status and details by ID.',
  list_jobs: 'List VoltMind jobs with optional filters.',
  cancel_job: 'Cancel a waiting, active, or delayed VoltMind job.',
  get_job_progress: 'Get structured progress for a running VoltMind job.',
  get_job_failure_report: 'Read recent VoltMind job failures without retrying or replaying them.',
  get_job_checkpoints: 'Read long-running VoltMind operation checkpoints without resuming workers.',
  get_job_undo_report: 'Build a read-only undo report for a VoltMind job; it does not execute undo.',
  plan_job_batch: 'Preview an explicit VoltMind batch plan without enqueueing jobs.',
  sources_add: 'Register a local source path with VoltMind.',
  sources_list: 'List registered VoltMind sources.',
  sources_remove: 'Remove a VoltMind source and its indexed pages.',
  sources_status: 'Return diagnostic status for one VoltMind source.',
  get_recent_salience: 'List recently salient VoltMind pages by activity, emotional weight, and active takes.',
  find_anomalies: 'Find statistically unusual recent VoltMind page activity by cohort.',
  find_experts: 'Rank people or companies in VoltMind that are relevant to a topic.',
  get_calibration_profile: 'Read the latest VoltMind calibration profile for a holder.',
  get_recent_transcripts: 'Read recent raw VoltMind conversation transcript summaries for retrieval grounding.',
  find_contradictions: 'Read suspected contradiction findings from the latest cached VoltMind probe run without launching a new probe.',
  find_trajectory: 'Read a source-scoped VoltMind trajectory for an entity without writing conclusions back.',
  takes_list: 'Read active VoltMind takes for a page, filtered by holder, kind, and status.',
  takes_search: 'Search active VoltMind takes by keyword without mutating take state.',
  recall: 'Read one-shot VoltMind memory recall results with provenance; no watch loop or cursor advancement.',
  preview_forget_fact: 'Preview a controlled fact forget without mutating DB or markdown.',
  apply_forget_fact: 'Apply a controlled fact forget with explicit confirm, source, and citation.',
  propose_extraction_candidates: 'Create a reviewable extraction candidate from an explicit source without writing brain content.',
  preview_candidate_apply: 'Preview the diff and risk of applying a pending candidate.',
  apply_candidate: 'Apply a pending candidate only with explicit confirm, source, and citation.',
  reject_candidate: 'Reject a pending candidate without changing brain content.',
};

const VOLTMIND_MVP_OPERATION_PARAMS: Record<string, string[]> = {
  query: ['query', 'limit', 'offset', 'expand', 'detail', 'source_id'],
  sync_brain: ['repo', 'dry_run', 'full', 'no_pull', 'no_embed'],
  preview_signal_enrichment: ['source_id', 'page_slug', 'text', 'limit', 'external'],
  apply_signal_enrichment: ['source_id', 'page_slug', 'text', 'limit', 'external', 'confirm'],
  sources_add: ['id', 'name', 'path'],
  sources_remove: ['id', 'confirm_destructive', 'dry_run', 'keep_storage'],
  get_job_progress: ['id'],
  get_job_failure_report: ['id', 'limit'],
  get_job_checkpoints: ['op', 'limit'],
  get_job_undo_report: ['id'],
  plan_job_batch: ['name', 'source_id', 'dry_run', 'limit'],
  get_recent_salience: ['days', 'limit', 'slugPrefix'],
  find_anomalies: ['since', 'lookback_days', 'sigma'],
  find_experts: ['topic', 'limit', 'explain'],
  get_calibration_profile: ['holder'],
  get_recent_transcripts: ['days', 'summary', 'limit'],
  find_contradictions: ['slug', 'severity', 'limit'],
  find_trajectory: ['entity_slug', 'metric', 'kind', 'since', 'until', 'limit'],
  takes_list: ['page_slug', 'holder', 'kind', 'active', 'resolved', 'sort_by', 'limit', 'offset'],
  takes_search: ['query', 'limit'],
  recall: ['entity', 'since', 'session_id', 'grep', 'limit', 'include_pending', 'include_expired', 'supersessions'],
  preview_forget_fact: ['id'],
  apply_forget_fact: ['id', 'reason', 'source_id', 'citation', 'confirm'],
  propose_extraction_candidates: ['source_id', 'page_slug', 'claim', 'citation', 'confidence', 'holder', 'kind', 'dry_run'],
  preview_candidate_apply: ['candidate_id'],
  apply_candidate: ['candidate_id', 'source_id', 'citation', 'confirm'],
  reject_candidate: ['candidate_id'],
};

export function isVoltMindMvpCliCommand(name: string): boolean {
  return VOLTMIND_MVP_CLI_COMMANDS.has(name);
}

export function isVoltMindMvpOperationName(name: string): boolean {
  return VOLTMIND_MVP_OPERATION_NAMES.has(name);
}

export function filterVoltMindMvpOperations(ops: Operation[]): Operation[] {
  return ops
    .filter(op => isVoltMindMvpOperationName(op.name))
    .map(op => {
      const description = VOLTMIND_MVP_OPERATION_DESCRIPTIONS[op.name];
      const paramNames = VOLTMIND_MVP_OPERATION_PARAMS[op.name];
      const params = paramNames
        ? Object.fromEntries(paramNames.flatMap(name => op.params[name] ? [[name, op.params[name]]] : []))
        : op.params;
      return description || params !== op.params ? { ...op, ...(description ? { description } : {}), params } : op;
    });
}

export function voltMindMvpUnavailableMessage(name: string): string {
  return `voltmind ${name} is not included in the VoltMind MVP runtime yet. ` +
    'The inherited GBrain implementation is kept in the repository for a later phase.';
}
