#!/usr/bin/env bun
import { readFileSync, writeFileSync } from 'node:fs';

const args = process.argv.slice(2);
function value(name: string): string | undefined {
  const index = args.indexOf(name);
  return index >= 0 ? args[index + 1] : undefined;
}

const commit = value('--commit') ?? 'development';
const jsonOut = value('--json-out');
if (commit !== 'development' && !/^[0-9a-f]{40}$/i.test(commit)) {
  throw new Error('--commit must be a 40-character SHA or development');
}
const version = readFileSync(new URL('../VERSION', import.meta.url), 'utf8').trim();
const embedded = readFileSync(new URL('../src/admin-embedded.ts', import.meta.url), 'utf8');
const adminMatch = embedded.match(/ADMIN_CONTENT_SHA256\s*=\s*["']([0-9a-f]{64})["']/i);
if (!adminMatch) throw new Error('src/admin-embedded.ts has no valid ADMIN_CONTENT_SHA256');
const provenance = {
  schema_version: 1,
  product: 'VoltMind',
  version,
  source_commit: commit,
  admin_content_sha256: adminMatch[1],
} as const;

const source = '// AUTO-GENERATED — do not edit by hand.\n'
  + '// Generated by scripts/write-release-provenance.ts.\n'
  + 'export const RELEASE_PROVENANCE = '
  + JSON.stringify(provenance, null, 2)
  + ' as const;\n';
writeFileSync(new URL('../src/release-provenance.ts', import.meta.url), source);
if (jsonOut) writeFileSync(jsonOut, JSON.stringify(provenance, null, 2) + '\n');
console.log(JSON.stringify(provenance));
